version: '3.8'

services:
  backend:
    image: darshana9/restaurant-backend:latest  # Change this
    container_name: restaurant_backend
    restart: always
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/project3
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - restaurant_network

  frontend:
    image: darshana9/restaurant-frontend:latest  # Change this
    container_name: restaurant_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - restaurant_network

networks:
  restaurant_network:
    driver: bridge